# .github/workflows/main.yml
name: Run Jest Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20.x"
      - run: npm install
      - run: npm test -- --ci --reporters=default --reporters=jest-junit
      - name: update Airtable
        if: always()
        run: node ./.scripts/main.js JS ${{github.actor}} https://github.com/${{github.repository}}
